### ISSUE TITLE
Fancy Front end!

### ISSUE THREAD

**Issue by abhinuvpitale** [abhinuvpitale/Pi-host-loader#1]
Change index.html to create a fancy page that accepts a message with 28 characters and also accepts a name and replicates current behavior

**Comment by PranavBhatia** [comment]
I am planning to work on this issue!

**Comment by ben1156** [comment]
Change  <title>Please leave your message here! (For a change, be creative!)</title>
     </head> to <title>Please leave your message here! </title> and make (For a change, be creative!) a header.

**Comment by abhinuvpitale** [comment]
Thanks Guys!
